[features]
seeds = false
skip-lint = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "mpl_metadata.so"

[programs.localnet]
defiraliacoin = "CeFVa5iijJASnRmMCvrHep8wVYRZ3XxAmgXArNJhpjmx"
[programs.devnet]
defiraliacoin = "CeFVa5iijJASnRmMCvrHep8wVYRZ3XxAmgXArNJhpjmx"
[programs.testnet]
defiraliacoin = "CeFVa5iijJASnRmMCvrHep8wVYRZ3XxAmgXArNJhpjmx"
[programs.mainnet]
defiraliacoin = "CeFVa5iijJASnRmMCvrHep8wVYRZ3XxAmgXArNJhpjmx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
